[context.production.environment]
HUGO_VERSION = "0.71.0"
HUGO_ENV = "production"

[[redirects]]
  from = "https://fostersamuel.com/*"
  to = "https://www.fostersamuel.com/:splat"
  status = 200
  force = true